export const routes = {
  home: '/',
  designs: '/designs',
  newDesign: '/new-design',
  customers: '/customers',
  more: '/more',
  quotes: '/quotes',
  pricingSettings: '/pricing-settings',
  companyProfile: '/company-profile',
  templateDetails: (templateId: string) => `/templates/${templateId}`,
  createDesignFromTemplate: (templateId: string) => `/templates/${templateId}/create`,
  designDetails: (designId: string) => `/designs/${designId}`,
  designEditor: (designId: string) => `/designs/${designId}/edit`,
  designQuote: (designId: string) => `/designs/${designId}/quote`,
  customerDetails: (customerId: string) => `/customers/${customerId}`,
} as const;
